// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsg7y_3rKKigcAU3zjAB8l-Bcu_iKeFRo',
    appId: '1:215021261043:web:528ef00f968dfe6333a786',
    messagingSenderId: '215021261043',
    projectId: 'shimishing-shield-ph',
    authDomain: 'shimishing-shield-ph.firebaseapp.com',
    storageBucket: 'shimishing-shield-ph.firebasestorage.app',
    measurementId: 'G-PX2EVKC485',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvgvWo1RTNXdBpgVHF817HCkUSq8sAwqQ',
    appId: '1:215021261043:android:39ee115708c1ff2133a786',
    messagingSenderId: '215021261043',
    projectId: 'shimishing-shield-ph',
    storageBucket: 'shimishing-shield-ph.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGnpUAoiCRtLuOYbiXROV8rfrJxntIz2M',
    appId: '1:215021261043:ios:2f7144a117feff0633a786',
    messagingSenderId: '215021261043',
    projectId: 'shimishing-shield-ph',
    storageBucket: 'shimishing-shield-ph.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGnpUAoiCRtLuOYbiXROV8rfrJxntIz2M',
    appId: '1:215021261043:ios:2f7144a117feff0633a786',
    messagingSenderId: '215021261043',
    projectId: 'shimishing-shield-ph',
    storageBucket: 'shimishing-shield-ph.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsg7y_3rKKigcAU3zjAB8l-Bcu_iKeFRo',
    appId: '1:215021261043:web:13df51d2375f0e1833a786',
    messagingSenderId: '215021261043',
    projectId: 'shimishing-shield-ph',
    authDomain: 'shimishing-shield-ph.firebaseapp.com',
    storageBucket: 'shimishing-shield-ph.firebasestorage.app',
    measurementId: 'G-0B683MWWTZ',
  );

}