// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPM1-xpCrC9yWQCoemdWBh44cwAHI7Vd4',
    appId: '1:556089083014:web:917d6874d8c4c104093d07',
    messagingSenderId: '556089083014',
    projectId: 'distilbert-based-smishing',
    authDomain: 'distilbert-based-smishing.firebaseapp.com',
    storageBucket: 'distilbert-based-smishing.firebasestorage.app',
    measurementId: 'G-5XHRMHS7V4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGEImJsmPKDulKbFhpnVZIQHWF4r6cMOs',
    appId: '1:556089083014:android:66bf334129e24750093d07',
    messagingSenderId: '556089083014',
    projectId: 'distilbert-based-smishing',
    storageBucket: 'distilbert-based-smishing.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWuddusA82lssetCCc3dVm02TgetxmQrU',
    appId: '1:556089083014:ios:9e704c15f8bfd065093d07',
    messagingSenderId: '556089083014',
    projectId: 'distilbert-based-smishing',
    storageBucket: 'distilbert-based-smishing.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWuddusA82lssetCCc3dVm02TgetxmQrU',
    appId: '1:556089083014:ios:9e704c15f8bfd065093d07',
    messagingSenderId: '556089083014',
    projectId: 'distilbert-based-smishing',
    storageBucket: 'distilbert-based-smishing.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPM1-xpCrC9yWQCoemdWBh44cwAHI7Vd4',
    appId: '1:556089083014:web:d6e5f8fe2c9c0daa093d07',
    messagingSenderId: '556089083014',
    projectId: 'distilbert-based-smishing',
    authDomain: 'distilbert-based-smishing.firebaseapp.com',
    storageBucket: 'distilbert-based-smishing.firebasestorage.app',
    measurementId: 'G-NDH3X2B7NT',
  );
}
